# Generated by Django 3.2.4 on 2023-05-22 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('slider1', models.ImageField(default=None, upload_to='uploads/')),
                ('slider2', models.ImageField(default=None, upload_to='uploads/')),
                ('slider3', models.ImageField(default=None, upload_to='uploads/')),
                ('slider4', models.ImageField(default=None, upload_to='uploads/')),
                ('slider5', models.ImageField(default=None, upload_to='uploads/')),
                ('slider6', models.ImageField(default=None, upload_to='uploads/')),
                ('address', models.CharField(max_length=100)),
                ('whatsapp', models.TextField()),
                ('instagram', models.TextField()),
                ('map', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialized', models.CharField(max_length=100)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.center')),
            ],
        ),
    ]
