# Generated by Django 3.2.4 on 2023-06-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='slider1',
            field=models.ImageField(default=None, upload_to='uploads/slider/<django.db.models.fields.CharField>'),
        ),
        migrations.AlterField(
            model_name='center',
            name='slider2',
            field=models.ImageField(default=None, upload_to='uploads/slider/<django.db.models.fields.CharField>'),
        ),
        migrations.AlterField(
            model_name='center',
            name='slider3',
            field=models.ImageField(default=None, upload_to='uploads/slider/<django.db.models.fields.CharField>'),
        ),
        migrations.AlterField(
            model_name='center',
            name='slider4',
            field=models.ImageField(default=None, upload_to='uploads/slider/<django.db.models.fields.CharField>'),
        ),
        migrations.AlterField(
            model_name='center',
            name='slider5',
            field=models.ImageField(default=None, upload_to='uploads/slider/<django.db.models.fields.CharField>'),
        ),
        migrations.AlterField(
            model_name='center',
            name='slider6',
            field=models.ImageField(default=None, upload_to='uploads/slider/<django.db.models.fields.CharField>'),
        ),
    ]
