# Generated by Django 3.2.4 on 2023-06-18 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20230618_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='center',
            name='name',
        ),
        migrations.AlterField(
            model_name='center',
            name='slider1',
            field=models.ImageField(default=None, upload_to='uploads/slider/name'),
        ),
    ]
