# Generated by Django 3.2.4 on 2023-07-03 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20230618_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='master',
        ),
        migrations.DeleteModel(
            name='Master',
        ),
        migrations.DeleteModel(
            name='Result',
        ),
    ]
