# Generated by Django 3.2.4 on 2023-07-15 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20230703_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='break_day',
            field=models.CharField(default='break', max_length=100, verbose_name='break'),
        ),
    ]
